{{- if (include "nri-metadata-injection.cluster" .) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nri-metadata-injection.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nri-metadata-injection.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "nri-metadata-injection.appLabel" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nri-metadata-injection.labels" . | nindent 8 }}
    spec:
      {{- if not .Values.customTLSCertificate }}
      serviceAccountName: {{ template "nri-metadata-injection.serviceAccountName" . }}
      {{- end }}
      containers:
      - name: {{ template "nri-metadata-injection.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
        - name: clusterName
          value: {{ include "nri-metadata-injection.cluster" . }}
        volumeMounts:
        - name: tls-key-cert-pair
          mountPath: /etc/tls-key-cert-pair
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
      volumes:
      - name: tls-key-cert-pair
        secret:
          secretName: {{ template "nri-metadata-injection.fullname" . }}
      {{- if $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
{{- end }}
