{{- if (and (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "nri-metadata-injection.fullname" . }}-job
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nri-metadata-injection.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "nri-metadata-injection.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "nri-metadata-injection.serviceAccountName" . }}
      containers:
      - name: {{ template "nri-metadata-injection.name" . }}-job
        # This is a minimal kubectl image based on Alpine Linux that sings certificates using the k8s extension api server
        image: "{{ .Values.jobImage.repository }}:{{ .Values.jobImage.tag }}"
        imagePullPolicy: "{{ .Values.jobImage.pullPolicy }}"
        command: ["./generate_certificate.sh"]
        args:
          - "--service"
          - {{ template "nri-metadata-injection.fullname" . }}
          - "--webhook"
          - {{ template "nri-metadata-injection.fullname" . }}
          - "--secret"
          - {{ template "nri-metadata-injection.fullname" . }}
          - "--namespace"
          - {{ .Release.Namespace }}
        {{- if .Values.jobImage.volumeMounts }}
        volumeMounts:
        {{- include "tplvalues.render" ( dict "value" .Values.jobImage.volumeMounts "context" $ ) | nindent 10 }}
        {{- end }}
      restartPolicy: Never
      {{- if .Values.jobImage.volumes }}
      volumes:
      {{- include "tplvalues.render" ( dict "value" .Values.jobImage.volumes "context" $ ) | nindent 8 }}
      {{- end }}
  backoffLimit: 1
{{- end }}
