{{- if (and .Values.serviceAccount.create (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nri-metadata-injection.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nri-metadata-injection.labels" . | nindent 4 }}
{{- end -}}
