dependencies:
  - name: newrelic-infrastructure
    repository: file://../newrelic-infrastructure
    condition: infrastructure.enabled
    version: 2.4.0

  - name: nri-prometheus
    repository: file://../nri-prometheus
    condition: prometheus.enabled
    version: 1.7.0

  - name: nri-metadata-injection
    repository: file://../nri-metadata-injection
    condition: webhook.enabled
    version: 1.4.1

  - name: kube-state-metrics
    repository: https://kubernetes.github.io/kube-state-metrics
    condition: ksm.enabled
    version: 2.13.2

  - name: nri-kube-events
    repository: file://../nri-kube-events
    condition: kubeEvents.enabled
    version: 1.8.0

  - name: newrelic-logging
    repository: file://../newrelic-logging
    condition: logging.enabled
    version: 1.4.7

