dependencies:
  - name: newrelic-infrastructure
    repository: file://../newrelic-infrastructure
    condition: infrastructure.enabled
    version: 2.0.1

  - name: nri-prometheus
    repository: file://../nri-prometheus
    condition: prometheus.enabled
    version: 1.5.1

  - name: nri-metadata-injection
    repository: file://../nri-metadata-injection
    condition: webhook.enabled
    version: 1.3.2

  - name: kube-state-metrics
    repository: https://charts.helm.sh/stable
    condition: ksm.enabled
    version: 2.9.1

  - name: nri-kube-events
    repository: file://../nri-kube-events
    condition: kubeEvents.enabled
    version: 1.4.0

  - name: newrelic-logging
    repository: file://../newrelic-logging
    condition: logging.enabled
    version: 1.4.3

