# Default values for nri-infrastructure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

infrastructure:
  enabled: true

prometheus:
  enabled: false

webhook:
  enabled: true

ksm:
  enabled: false

kubeEvents:
  enabled: false

logging:
  enabled: false

# IMPORTANT: the following values are set as global so that they
# can be shared by other newrelic product's charts
#
#   - Specify either the New Relic keys or the secret which
#   contains them.
#
#   - Specify the Kubernetes cluster name.
#     https://docs.newrelic.com/docs/kubernetes-monitoring-integration
#
# global:
#   licenseKey:
#   insightsKey:
#   customSecretName:
#   customSecretLicenseKey:
#   customSecretInsightsKey:
#   cluster:
