apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  labels: {{ include "newrelic-logging.labels" . | indent 4 }}
  name: {{ template "newrelic-logging.fluentBitConfig" . }}
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
      Flush         1
      Log_Level     ${LOG_LEVEL}
      Daemon        off
      Parsers_File  C:\\fluent-bit\\conf\\parsers.conf
      HTTP_Server   Off
      HTTP_Listen   0.0.0.0
      HTTP_Port     2020

    [INPUT]
      Name              tail
      Tag               kube.*
      Path              ${PATH}
      Parser            docker
      DB                C:\\fluent-bit\\tail_docker.db
      Mem_Buf_Limit     7MB
      Refresh_Interval  10

    [INPUT]
      Name              tail
      Tag               kubelet.err
      Path              C:\\k\\kubelet.err.log
      DB                C:\\fluent-bit\\tail_kubelet.db

    [FILTER]
      Name                kubernetes
      Match               kube.*
      Kube_URL            https://kubernetes.default.svc.cluster.local:443

    [FILTER]
      Name           record_modifier
      Match          *
      Record         cluster_name ${CLUSTER_NAME}

    [OUTPUT]
      Name  newrelic
      Match *
      licenseKey ${LICENSE_KEY}
      endpoint ${ENDPOINT}