global:
  licenseKey: 1234567890abcdef1234567890abcdef12345678
  cluster: test-cluster

# install everything
infrastructure:
  enabled: true

prometheus:
  enabled: true

webhook:
  enabled: true

ksm:
  enabled: true

kubeEvents:
  enabled: true

logging:
  enabled: true
