# IMPORTANT: Specify your New Relic API key here.
# licenseKey:
#
# Optionally, specify a cluster name and log records can
# be filtered by cluster.
# cluster:
#
# or Specify secret which contains New Relic API key
# customSecretName: secret_name
# customSecretLicenseKey: secret_key
#
# The previous values can also be set as global so that they
# can be shared by other newrelic product's charts
#
# global:
#   licenseKey:
#   cluster:
#   customSecretName:
#   customSecretLicenseKey:
#
# IMPORTANT: if you use a kubernetes secret to specify the license,
# you have to manually provide the correct endpoint depending on
# whether your account is for the EU region or not.
#
# endpoint: https://log-api.newrelic.com/log/v1

fluentBit:
  logLevel: "info"
  path: "/var/log/containers/*.log"
  criEnabled: false
  k8sLoggingExclude: "Off"
  # filters - optinal field used to add additional filters to the FluentBit configuration.
  #
  # Example:
  #
  # Kubernetes saves log files in /var/log/containers/<namespace>_<pod_name>_<pod_id>/<container_name>/
  # This chart already defines a filter that adds the tag kube.* (see
  # https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#workflow-of-tail-kubernetes-filter).
  #
  # The following filter adds the attribute logtype=nginx to any log with 'nginx' in the pod name,namespace
  # or container name.

  # filters: |
  #    [FILTER]
  #        Name           record_modifier
  #        Match          kube.var.log.containers.*nginx*
  #        Record         logtype nginx

image:
  repository: newrelic/newrelic-fluentbit-output
  tag: ""
  pullPolicy: IfNotPresent
  ## See https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  # pullSecrets:
    # - name: regsecret

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  pspEnabled: false

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# If you wish to provide additional labels to apply to the pod(s), specify
# them here
# podLabels:

# Pod scheduling proirity
# Ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
# priorityClassName: high-priority

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# These are default tolerations to be able to run the New Relic Kubernetes
# integration.
tolerations:
  - operator: "Exists"
    effect: "NoSchedule"
  - operator: "Exists"
    effect: "NoExecute"

updateStrategy: RollingUpdate

# Sends data to staging, can be set as a global.
# global.nrStaging
nrStaging: false
