{{- define "fargate-config" -}}
infraAgentInjection:
  resourcePrefix: {{ template "newrelic-infra-operator.fullname" . }}
{{- end -}}


{{- define "config" -}}
{{ toYaml (merge (include "fargate-config" . | fromYaml) .Values.config) }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "newrelic-infra-operator.fullname" . }}-config
  labels:
    {{- include "newrelic-infra-operator.labels" . | nindent 4 }}
data:
  operator.yaml: {{- include "config" . | toYaml | nindent 4  }}
