{{- if .Values.rbac.create }}
{{- if .Values.etcdTlsSecretNamespace}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: {{ include "newrelic.labels" . | indent 4 }}
  name: {{ template "newrelic.fullname" . }}-secrets
  namespace: {{ .Values.etcdTlsSecretNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "newrelic.fullname" . }}-secrets
subjects:
- kind: ServiceAccount
  name: {{ template "newrelic.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
