apiVersion: v1
description: A Helm chart to deploy the New Relic Infrastructure Agent as a DaemonSet
name: newrelic-infrastructure
<<<<<<< HEAD
version: 1.5.0
appVersion: 1.26.1
=======
version: 1.3.4
appVersion: 1.26.4
>>>>>>> 57f54ed56cf787c9f4f8468ac686eca8fd5bfee5
home: https://hub.docker.com/r/newrelic/infrastructure-k8s/
source:
  - https://github.com/kubernetes/kubernetes/tree/master/examples/newrelic-infrastructure
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: rk295
    email: robin@kearney.co.uk
  - name: jfjoly
    email: jjoly@newrelic.com
  - name: areina
  - name: douglascamata
  - name: jorik
  - name: alejandrodnm
  - name: rk295
keywords:
  - infrastructure
  - newrelic
  - monitoring
