name: 'Chart version bumper'
description: 'Bump a Helm chart & app version'
inputs:
  chart_name: 
    description: 'Name of the chart'
    required: true
outputs:
  time: 
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'