name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v1
      - uses: actions/setup-python@v2

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Lint charts
        run: ct lint --config ct.yaml

      - name: Check for changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.1.0
      - name: Create test ns
        if: steps.list-changed.outputs.changed == 'true'
        run: kubectl create ns ct

      - name: Test install charts
        run: ct install --namespace ct --config ct.yaml
